import { randomUUID } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createFoundryDatabase } from "../../services/foundry-service/src/database/client.js";
import type { FoundryDatabase } from "../../services/foundry-service/src/database/types.js";
import { createOperationsDomain } from "../../services/foundry-service/src/domain/operations.js";
import { createQuotasDomain } from "../../services/foundry-service/src/domain/quotas.js";
import type { Kysely } from "kysely";

const enabled=process.env.PHASE_0N_INTEGRATION==="1";const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");const compose=path.join(root,"scripts","compose.sh");const key=randomUUID().slice(0,8);let container="",password="",db:Kysely<FoundryDatabase>;const tenants:string[]=[];
function sqlRun(sql:string){return spawnSync("docker",["exec","-e",`PGPASSWORD=${password}`,container,"psql","-X","-v","ON_ERROR_STOP=1","--host","127.0.0.1","--username","expense_foundry_runtime","--dbname","expense_tax_db","--tuples-only","--no-align","--pset","footer=off","--command",sql],{encoding:"utf8"})}
function sql(sql:string){const r=sqlRun(sql);if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim()}
describe.skipIf(!enabled)("Phase 0N Foundry operations reads",()=>{beforeAll(()=>{const config=JSON.parse(execFileSync(compose,["config","--format","json"],{cwd:root,encoding:"utf8"})) as{services:Record<string,{environment?:Record<string,string|null>}>};container=execFileSync(compose,["ps","-q","postgres"],{cwd:root,encoding:"utf8"}).trim();password=config.services.postgres?.environment?.FOUNDRY_RUNTIME_DB_PASSWORD??"";db=createFoundryDatabase(`postgresql://expense_foundry_runtime:${encodeURIComponent(password)}@127.0.0.1:5433/expense_tax_db`)});afterAll(async()=>{for(const tenant of tenants){sql(`DELETE FROM foundry.provider_call_logs WHERE reservation_id IN (SELECT id FROM foundry.ai_quota_reservations WHERE tenant_id='${tenant}');DELETE FROM foundry.ai_quota_reservation_resolutions WHERE reservation_id IN (SELECT id FROM foundry.ai_quota_reservations WHERE tenant_id='${tenant}');DELETE FROM foundry.ai_quota_reservations WHERE tenant_id='${tenant}';DELETE FROM foundry.ai_quota_periods WHERE tenant_ai_quota_id IN (SELECT id FROM foundry.tenant_ai_quotas WHERE tenant_id='${tenant}');DELETE FROM foundry.tenant_ai_quotas WHERE tenant_id='${tenant}';`)}sql(`DELETE FROM foundry.foundry_audit_events WHERE request_id LIKE '0n-${key}-%'`);await db.destroy()});it("returns periods, calls, reconciliation evidence, and audit",async()=>{const tenant=randomUUID();tenants.push(tenant);const q=createQuotasDomain(db);await q.createTenantAiQuota({request:{tenantId:tenant,operation:"RECEIPT_OCR",aiModelId:null,periodType:"monthly",maxJobs:10},actorPlatformSubject:"operator",requestId:`0n-${key}-policy`});const r=await q.reserve({request:{tenantId:tenant,operation:"RECEIPT_OCR",aiModelId:"eeeeeeee-0001-4000-8000-000000000003",idempotencyKey:`0n-${key}`},requestId:`0n-${key}-reserve`});await q.recordCallAttempt({reservationId:r.id,request:{},requestId:`0n-${key}-call`});await q.markReconciliationRequired({reservationId:r.id,requestId:`0n-${key}-reconcile`});const ops=createOperationsDomain(db);expect((await ops.listQuotaPeriods(100)).some(x=>x.tenantId===tenant)).toBe(true);expect((await ops.listProviderCalls(100)).some(x=>x.reservationId===r.id)).toBe(true);const queue=(await ops.listReconciliationQueue(100)).find(x=>x.reservationId===r.id);expect(queue?.attempts).toHaveLength(1);expect(queue?.releasedApprovalCount).toBe(0);expect((await ops.listAuditEvents(100)).some(x=>x.requestId===`0n-${key}-policy`)).toBe(true)})});
